### PR TITLE
Skills ml tour

### PR DESCRIPTION
**Pull request by tweddielin**
- Skills-ML tour notebook

### CODE REVIEW

**Comment by thcrock** [comment]
My first comment is that defining the utility functions at the top of the notebook is confusing. The top of the notebook (or at least clearly visible on the first page) should be the intro text. I think you should either:

1. Move the functions to actual modules.
2. Define each function within the notebook right before it is first used.

**Comment by thcrock** [comment]
Only other comment: Could you either rerun it with logging WARNING so it's not so gigantic? Or just remove the huge blocks of INFO logs in some of the output sections?

**Comment by thcrock** [comment]
Generally looks good but I think the two comments above will make it much easier to browse.

**Comment by tweddielin** [comment]
I added only `itershuffle` function to skills_ml.utils in the end. The other helper functions stay in the notebook since they are more customized.

**Pull request merged**
